# Generated by Django 5.2.17 on 2026-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Open', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acceptance_criteria', models.JSONField(default=list)),
            ],
        ),
    ]
