# Generated by Django 5.2.17 on 2026-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_mock', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
